[tool.poetry]
name = "digitalzone"
version = "0.1.0"
description = ""
authors = ["Denis_Oreshnikov <supermeatden@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
